/* Generated by Yosys 0.66+70 (git sha1 8eb313307, Release, GNU /usr/bin/x86_64-w64-mingw32-g++ 13.2.1) */

(* dynports =  1  *)
(* hdlname = "accumulator" *)
(* src = "rtl/accumulator.v:4.1-48.10" *)
module \$paramod$7e12df99be1db7df5394382489cfc1918a0dcf9b\accumulator (clk, rst, valid_in, product_in, acc_out, overflow_flag);
  (* src = "rtl/accumulator.v:10.39-10.42" *)
  input clk;
  wire clk;
  (* src = "rtl/accumulator.v:11.39-11.42" *)
  input rst;
  wire rst;
  (* src = "rtl/accumulator.v:12.39-12.47" *)
  input valid_in;
  wire valid_in;
  (* src = "rtl/accumulator.v:13.39-13.49" *)
  input [15:0] product_in;
  wire [15:0] product_in;
  (* src = "rtl/accumulator.v:14.39-14.46" *)
  output [15:0] acc_out;
  reg [15:0] acc_out;
  (* src = "rtl/accumulator.v:15.39-15.52" *)
  output overflow_flag;
  reg overflow_flag;
  wire _00_;
  wire _01_;
  wire _02_;
  (* src = "rtl/accumulator.v:24.33-24.80" *)
  wire _03_;
  (* src = "rtl/accumulator.v:25.33-25.78" *)
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  (* src = "rtl/accumulator.v:18.33-18.41" *)
  wire [15:0] next_acc;
  (* src = "rtl/accumulator.v:19.33-19.50" *)
  wire overflow_detected;
  assign next_acc = $signed(acc_out) + (* src = "rtl/accumulator.v:21.23-21.43" *) $signed(product_in);
  (* src = "rtl/accumulator.v:27.5-46.8" *)
  always @(posedge clk)
    if (rst) acc_out <= 16'h0000;
    else if (_00_) acc_out <= next_acc;
  (* src = "rtl/accumulator.v:27.5-46.8" *)
  always @(posedge clk)
    if (rst) overflow_flag <= 1'h0;
    else overflow_flag <= _07_;
  assign _00_ = & { valid_in, _01_, _02_ };
  assign _01_ = ~ overflow_detected;
  assign _02_ = ~ overflow_flag;
  assign _03_ = acc_out[15] == (* src = "rtl/accumulator.v:24.33-24.80" *) product_in[15];
  assign overflow_detected = _03_ && (* src = "rtl/accumulator.v:24.32-25.79" *) _04_;
  assign _04_ = next_acc[15] != (* src = "rtl/accumulator.v:25.33-25.78" *) acc_out[15];
  assign _05_ = overflow_detected ? (* full_case = 32'd1 *) (* src = "rtl/accumulator.v:35.17-35.34|rtl/accumulator.v:35.13-41.16" *) 1'h1 : 1'h0;
  assign _06_ = valid_in ? (* full_case = 32'd1 *) (* src = "rtl/accumulator.v:34.22-34.30|rtl/accumulator.v:34.18-45.12" *) _05_ : 1'h0;
  assign _07_ = overflow_flag ? (* full_case = 32'd1 *) (* src = "rtl/accumulator.v:31.22-31.35|rtl/accumulator.v:31.18-45.12" *) 1'h1 : _06_;
endmodule

(* dynports =  1  *)
(* hdlname = "multiplier_array" *)
(* src = "rtl/multiplier_array.v:4.1-55.10" *)
module \$paramod\multiplier_array\WIDTH=s32'00000000000000000000000000001000 (a, b, product);
  (* src = "rtl/multiplier_array.v:9.37-9.38" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/multiplier_array.v:10.37-10.38" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/multiplier_array.v:11.37-11.44" *)
  output [15:0] product;
  wire [15:0] product;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _00_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _01_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _02_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _03_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _04_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _05_;
  (* src = "rtl/multiplier_array.v:39.5-47.8" *)
  wire [15:0] _06_;
  (* src = "rtl/multiplier_array.v:33.40-33.56" *)
  wire [7:0] _07_;
  (* src = "rtl/multiplier_array.v:34.40-34.56" *)
  wire [7:0] _08_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _09_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _10_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _11_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _12_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _13_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _14_;
  (* src = "rtl/multiplier_array.v:44.36-44.78" *)
  wire [15:0] _15_;
  (* src = "rtl/multiplier_array.v:50.35-50.61" *)
  wire [15:0] _16_;
  (* src = "rtl/multiplier_array.v:33.41-33.48" *)
  wire [7:0] _17_;
  (* src = "rtl/multiplier_array.v:34.41-34.48" *)
  wire [7:0] _18_;
  (* src = "rtl/multiplier_array.v:50.36-50.53" *)
  wire [15:0] _19_;
  (* src = "rtl/multiplier_array.v:16.30-16.36" *)
  wire [7:0] a_bits;
  (* src = "rtl/multiplier_array.v:18.30-18.41" *)
  wire [7:0] a_magnitude;
  (* src = "rtl/multiplier_array.v:17.30-17.36" *)
  wire [7:0] b_bits;
  (* src = "rtl/multiplier_array.v:19.30-19.41" *)
  wire [7:0] b_magnitude;
  (* src = "rtl/multiplier_array.v:26.13-26.14" *)
  wire [31:0] i;
  (* src = "rtl/multiplier_array.v:21.30-21.46" *)
  wire [15:0] multiplicand_ext;
  (* src = "rtl/multiplier_array.v:20.30-20.46" *)
  wire product_negative;
  (* src = "rtl/multiplier_array.v:22.30-22.49" *)
  wire [15:0] signed_product_bits;
  (* src = "rtl/multiplier_array.v:24.30-24.46" *)
  wire [15:0] unsigned_product;
  assign _07_ = _17_ + (* src = "rtl/multiplier_array.v:33.40-33.56" *) 1'h1;
  assign _08_ = _18_ + (* src = "rtl/multiplier_array.v:34.40-34.56" *) 1'h1;
  assign _09_ = _00_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 7'h00, a_magnitude, 1'h0 };
  assign _10_ = _01_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 6'h00, a_magnitude, 2'h0 };
  assign _11_ = _02_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 5'h00, a_magnitude, 3'h0 };
  assign _12_ = _03_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 4'h0, a_magnitude, 4'h0 };
  assign _13_ = _04_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 3'h0, a_magnitude, 5'h00 };
  assign _14_ = _05_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 2'h0, a_magnitude, 6'h00 };
  assign _15_ = _06_ + (* src = "rtl/multiplier_array.v:44.36-44.78" *) { 1'h0, a_magnitude, 7'h00 };
  assign _16_ = _19_ + (* src = "rtl/multiplier_array.v:50.35-50.61" *) 1'h1;
  assign _17_ = ~ (* src = "rtl/multiplier_array.v:33.41-33.48" *) a;
  assign _18_ = ~ (* src = "rtl/multiplier_array.v:34.41-34.48" *) b;
  assign _19_ = ~ (* src = "rtl/multiplier_array.v:50.36-50.53" *) unsigned_product;
  assign unsigned_product = b_magnitude[7] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _15_ : _06_;
  assign _06_ = b_magnitude[6] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _14_ : _05_;
  assign _05_ = b_magnitude[5] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _13_ : _04_;
  assign _04_ = b_magnitude[4] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _12_ : _03_;
  assign _03_ = b_magnitude[3] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _11_ : _02_;
  assign _02_ = b_magnitude[2] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _10_ : _01_;
  assign _01_ = b_magnitude[1] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) _09_ : _00_;
  assign _00_ = b_magnitude[0] ? (* full_case = 32'd1 *) (* src = "rtl/multiplier_array.v:43.17-43.31|rtl/multiplier_array.v:43.13-45.16" *) { 8'h00, a_magnitude } : 16'h0000;
  assign a_magnitude = a[7] ? (* src = "rtl/multiplier_array.v:33.26-33.66" *) _07_ : { 1'h0, a[6:0] };
  assign b_magnitude = b[7] ? (* src = "rtl/multiplier_array.v:34.26-34.66" *) _08_ : { 1'h0, b[6:0] };
  assign product = product_negative ? (* src = "rtl/multiplier_array.v:49.34-51.50" *) _16_ : unsigned_product;
  assign product_negative = a[7] ^ (* src = "rtl/multiplier_array.v:36.31-36.54" *) b[7];
  assign i = 32'd8;
  assign signed_product_bits = product;
  assign multiplicand_ext = { 8'h00, a_magnitude };
  assign b_bits = b;
  assign a_bits = a;
endmodule

(* dynports =  1  *)
(* top =  1  *)
(* src = "rtl/mac_top.v:4.1-49.10" *)
module mac_top(clk, rst, valid_in, a, b, acc_out, overflow_flag);
  (* src = "rtl/mac_top.v:10.39-10.42" *)
  input clk;
  wire clk;
  (* src = "rtl/mac_top.v:11.39-11.42" *)
  input rst;
  wire rst;
  (* src = "rtl/mac_top.v:12.39-12.47" *)
  input valid_in;
  wire valid_in;
  (* src = "rtl/mac_top.v:13.39-13.40" *)
  input [7:0] a;
  wire [7:0] a;
  (* src = "rtl/mac_top.v:14.39-14.40" *)
  input [7:0] b;
  wire [7:0] b;
  (* src = "rtl/mac_top.v:15.39-15.46" *)
  output [15:0] acc_out;
  wire [15:0] acc_out;
  (* src = "rtl/mac_top.v:16.39-16.52" *)
  output overflow_flag;
  wire overflow_flag;
  (* src = "rtl/mac_top.v:19.33-19.40" *)
  wire [15:0] product;
  (* src = "rtl/mac_top.v:39.5-47.6" *)
  \$paramod$7e12df99be1db7df5394382489cfc1918a0dcf9b\accumulator  u_accumulator (
    .acc_out(acc_out),
    .clk(clk),
    .overflow_flag(overflow_flag),
    .product_in(product),
    .rst(rst),
    .valid_in(valid_in)
  );
  (* src = "rtl/mac_top.v:27.5-32.6" *)
  \$paramod\multiplier_array\WIDTH=s32'00000000000000000000000000001000  u_multiplier_array (
    .a(a),
    .b(b),
    .product(product)
  );
endmodule
